// Code generated by lister-gen. DO NOT EDIT.

package v1

// TFJobListerExpansion allows custom methods to be added to
// TFJobLister.
type TFJobListerExpansion interface{}

// TFJobNamespaceListerExpansion allows custom methods to be added to
// TFJobNamespaceLister.
type TFJobNamespaceListerExpansion interface{}
